server:
    port: 8084
    error:  include-message=always
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MovieBookingApp_Database?createDatabaseIfNotExist=true
    username: MovieBookingApp_Database
    password: admin
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
  kafka:
    template:
          default-topic: topic1
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset:  latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer